CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Models/Factory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace GalacticFactories.Web.Models
{
    public class Factory
    {
        [Display(Name = "Factory id")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Factory Name")]
        [Required]
        [StringLength(30, MinimumLength = 3)]
        public string FactoryName { get; set; }

        [Display(Name = "Factory Planet")]
        [Required]
        public string Planet { get; set; }

        [Display(Name = "Factory Leader")]
        [Required]
        public string Leader { get; set; }

        [Display(Name = "Factory Side")]
        [Required]
        public string Side { get; set; }

        [Display(Name = "Factory Strategic Value")]
        [Required]
        public int StrategicValue { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Models/FactoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GalacticFactories.Web.Models
{
    public class FactoryViewModel
    {
        public Factory EditFactory { get; set; }
        public List<Factory> ListOfFactories { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Controllers/FactoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using GalacticFactories.Data;
using GalacticFactories.Repository;
using GalacticFactories.Logic;
using GalacticFactories.Web.Models;

namespace GalacticFactories.Web.Controllers
{
    public class FactoryController : Controller
    {
        ILogic logic;
        IMapper mapper;
        FactoryViewModel model;
        
        public FactoryController()
        {
            GalacticFactoriesEntities ctx = new GalacticFactoriesEntities();
            Repository.Repository repo = new Repository.Repository(ctx);
            logic = new Logic.Logic(repo);
            mapper = MapperFactory.CreateMapper();
            model = new FactoryViewModel();
            model.EditFactory = new Factory();

            var factories = logic.FactoriesGetAll();
            model.ListOfFactories = mapper.Map<IEnumerable<Data.Factories>, List<Models.Factory>>(factories);
        }

        private Factory GetFactoryModel(int id)
        {
            Factories oneFactory = logic.GetOneFactory(id);
            return mapper.Map<Factories, Factory>(oneFactory);
        }

        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("FactoryIndex", model);
        }

        // GET: Factory/Details/5
        public ActionResult Details(int id)
        {
            return View("FactoryDetails", GetFactoryModel(id));
        }

        public ActionResult Remove(int id)
        {
            logic.FactoryDelete(id);
            TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        // GET: Factory/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            model.EditFactory = GetFactoryModel(id);
            return View("FactoryIndex", model);
        }

        // POST: Factory/Edit/5
        [HttpPost]
        public ActionResult Edit(Factory factory, string editAction)
        {
            if (ModelState.IsValid && factory != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.FactoryCreate(factory.FactoryName, factory.Planet, factory.Leader, factory.Side, factory.StrategicValue);
                }
                else
                {
                    if (!logic.ChangeFactory(factory.Id, factory.FactoryName, factory.Planet, factory.Leader, factory.Side, factory.StrategicValue))
                    {
                        TempData["editResult"] = "Edit Fail";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                model.EditFactory = factory;
                return View("FactoryIndex", model);
            }
        }
    }
}

CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Views/Factory/FactoryDetails.cshtml
@model GalacticFactories.Web.Models.Factory

@{
    ViewBag.Title = "FactoryDetails";
}

<h2>Datasheet if one factory</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FactoryName)</td>
        <td>@Html.DisplayFor(m => m.FactoryName)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Planet)</td>
        <td>@Html.DisplayFor(m => m.Planet)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Leader)</td>
        <td>@Html.DisplayFor(m => m.Leader)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Side)</td>
        <td>@Html.DisplayFor(m => m.Side)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.StrategicValue)</td>
        <td>@Html.DisplayFor(m => m.StrategicValue)</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Views/Factory/FactoryEdit.cshtml
@model GalacticFactories.Web.Models.Factory
@{
    ViewBag.Title = "FactoryEdit";
}

<h2>FactoryEdit</h2>

@using (Html.BeginForm("Edit", "Factory"))
{
    @Html.ValidationSummary();
    @Html.AntiForgeryToken();

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.FactoryName)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FactoryName)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Planet)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Planet)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Leader)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Leader)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Side)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Side)</div>

    <div class="editor-label">@Html.LabelFor(m => m.StrategicValue)</div>
    <div class="editor-field">@Html.EditorFor(m => m.StrategicValue)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Views/Factory/FactoryIndex.cshtml
@model GalacticFactories.Web.Models.FactoryViewModel

@{ 
    ViewBag.Title = "Crud Index";
}

<h2>Factory Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@Html.Partial("FactoryEdit", Model.EditFactory)

@Html.Partial("FactoryList", Model.ListOfFactories)

CSHARP/OENIK_PROG3_2019_1_X7IKPT/GalacticFactories.Web/Views/Factory/FactoryList.cshtml
@model IEnumerable<GalacticFactories.Web.Models.Factory>
@{
    ViewBag.Title = "FactoryList";
}

<h2>FactoryList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().FactoryName)</th>
            <th>@Html.DisplayNameFor(m => m.First().Planet)</th>
            <th>DataSheet</th>
            <th>Delete</th>
            <th>Edit</th>>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.FactoryName)</td>
                <td>@Html.DisplayFor(m => item.Planet)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}